### ISSUE TITLE
Feedback: Importing

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypepy#10]
It is very important that your test files import the functions they are testing rather than copying the functions to it's own file. As written, your tests aren't testing the actual functions, but copies of the functions. This will introduce bugs because when you run your test suite they won't actually test the latest version of each function.

**Comment by joesdesk** [comment]
Which set of files/functions does this refer to?

**Comment by vmasrani** [comment]
I'm assuming your final code will go within src/*.py. Your four test scripts in tests/*.py should import the files from hypepy/src/*.py and test those functions, rather than duplicating the functions within the test script itself. For example in hyp_test_testing.py the function hyp_test() is copy-pasted into the test script. This will cause headaches down the line because you'll only be testing the copied version, not the latest version.

**Comment by joesdesk** [comment]
Addressed in commit bad6a2d7.
