### ISSUE TITLE
Feedback: Requirements file

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypepy#29]
Include a [requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html) file with a list of packages (numpy, etc) hypepy requires. Also in the readme, include the python version (2.7 or 3.6) your package has been tested on.

**Comment by joesdesk** [comment]
I've been reading more about the requirements.txt file vs install_requires (in setup.py) in https://packaging.python.org/discussions/install-requires-vs-requirements/. I'm a bit confused between the two ways of specifying dependencies for the project. Can you elaborate on the explanation in the discussion linked above.

**Comment by vmasrani** [comment]
For sure - requirements.txt is nothing more than a list of python packages the user should install before running the package. So rather than the user manually entering something like 
```bash
pip install numpy scipy matplotlib pandas seaborn
```
etc etc, they would instead run the command:
```bash
pip install -r requirements.txt
```
And it would install all those packages.

install_requires is essentially the same thing, except it's folded into the setup.py file. You should use the install_requires method for your project, but it's good to be aware of requirements.txt because you'll often see it used.

**Comment by joesdesk** [comment]
Thanks. We've used install_requires and learned about requirements.txt.
