### ISSUE TITLE
Feedback: Default values

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypepy#8]
- Python default values should be specified as:
`def hyp_test(data, mean=0):
    pass
`

**Comment by joesdesk** [comment]
I thought the functions should be empty so that they are expected to fail. I didn't guess that you'd want the default values to be correct? Will this affect our grades?

**Comment by vmasrani** [comment]
No it was just some info about how to specify a default value (mean=0 rather than mean_0).

**Comment by vmasrani** [comment]
Okay gotcha.

**Comment by joesdesk** [comment]
Sorry for the confusion...
