### ISSUE TITLE
Feedback: hyp_test_testing.py

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/hypepy#9]
- In hyp_test_testing.py you pass in the 'hyp_test' function into the three test functions. This is unnecessary as 'hyp_test' is global and therefore callable from within each test function. 
- The 'hyp_test_missing' function is incorrect; where is 'data' defined? How is data being passed to hyp_test?  Remember you're testing how the functions handle the data, not the data itself. You need to write something like:
```
 def hyp_test_missing(hyp_test):
        '''
        Test if the input contains missing values.
        '''
        data = np.array([0, np.nan, 2])
        with pytest.raises(TypeError):
            hyp_test(data, mean=0)    
            assert data == np.isnan(data)

```
- All the function call to hyp_test in hyp_test_testing.py are missing the mean parameter. If you add a default value this won't be an issue but as written they will crash.
- 
```
def hyp_test_non_zero(hyp_test):
'''
Test that the length of the data is greater than 0.
'''
    assert len(hyp_test) > 0
```
This isn't going to work - hyp_test is a function, not a datatype. Again you need to write something like:
```
def hyp_test_non_zero(hyp_test):
  with pytest.raises(ValueError):
      data = np.array([])
      hyp_test(data)
```

**Comment by joesdesk** [comment]
Will we be marked on the "run"-ability of these testing functions? I.e. is it sufficient that the test functions fail because the test code themselves have bugs? Or should the test functions fail because the contents of functions they are testing are empty?

**Comment by vmasrani** [comment]
The second - at this point, they should fail because the test functions are empty. Once you start writing the code they should pass only once the functions themselves are working correctly. Yes, there are marks assigned for the quality/runnability of the code. You'll be using these test functions in the future, so they should work.

**Comment by Ivan-Despot** [comment]
The changes were made to the test functions. Thank you for the thorough explanation, Vaden.
